In [16]:
import pandas
from konlpy.tag import Komoran
from gensim.models import word2vec
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import string
import re
import sys

In [17]:
#파일 읽어오기
file = open('C:/Users/student/Documents/GitHub/Moons/분석/test3.txt','r',encoding='utf-8')
line = file.read()

#장(chapter)마다 나눔
sentences = re.split('(?<=[2-9]\n)|(?<=[0-9][0-9]\n)|(?<=[0-9][0-9][0-9]\n)', line)


#Komoran 형태소 분석을 위한 전처리
sent=[]
for stuff in sentences:
#         stuff = stuff.replace("'","").replace("?","").replace(".","").replace("'","").replace('"'
# ,"").replace("!","").replace("-","").replace('"',"").replace("\n","")
#         stuff = re.sub("\n","", line).strip()
        stuff= "\n".join([s for s in stuff.split("\n") if s])
        sent.append(stuff)

In [18]:
print(sent)

다. 그러나 두 사람은 보지 못한 것 같다. 형식은 ‘어찌하나’ 하고, 선형은 ‘조 요물이’ 하였다. 병욱이가 뛰어가서, “얘, 우리도 내리자. 저이들도 내리시는데” 하고 뒤를 돌아보는 것을 보고야 비로소 영채도 형식과 선형을 보았다. 그러고 얼른 고개를 움촐하였다.\n병욱이가 앞서고 영채는 병욱의 뒤에 서서 병욱의 그늘에 자기의 몸을 감추려는 듯이 비실비실 형식의 곁으로 온다. 병욱이가 실적 빗겨 서매 영채와 형식과는 정면으로 마주서게 되었다. 영채는 형식에게 가볍게 고개를 숙이고 다음에 선형을 향하고 방그레 웃으며 은근하게 인사를 하였다. 선형도 웃으며 답례하였다. 그러나 둘이 다 일시에 얼굴을 붉혔다.\n네 사람은 열을 지어서 개찰구를 나섰다. 일없는 손님들은 네 사람의 행색을 유심히 보며 혹 웃기도 하고 수군수군하기도 한다. 마치 형식이가 세 누이를 데리고 가는 것 같다. 대합실에서 여관 하인에게 짐을 맡기고 네 사람은 그 하인의 뒤를 따라 나가다가 정거장 모퉁이에 서서 붉은 물이 굽실굽실하는 낙동강을 본다.\n119', '“아니, 저 물 보셔요!” 하고 병욱이가 가시 돋은 철사에 배를 대고 허리를 굽히며 소리를 친다. 다른 세 사람도 속으로는 ‘저 물 보게’ 하면서도 아무도 입 밖에 말을 내지는 아니한다.\n“저것 보게. 저기 저 집들이 반이나 잠겼습니다그려!” 하고 마산선으로 갈려 나가는 길가에 있는 초가집들을 가리킨다. 과연 대단한 물이로다. 좌우편 산을 남겨 놓고는 온통 시뻘건 흙물이로다. 강 한가운데로 굼실굼실 소용돌이를 쳐가며 흘러내려가는 물소리가 들리는 듯하고 그 물들이 좌우편에 늘어선 산굽이를 파서 얼마 아니 되면 그 산들의 밑이 빠져 나갈 것 같다.\n길이 좁아서 미처 빠지지를 못하여 우묵우묵한 웅커리(웅덩이)라는 웅커리는 하나도 남겨 놓지 않고 쓸어들여서 진을 치고 앞선 물들이 다 내려가기를 기다리는 것 같다. 길을 잃은 물은 사람 사는 촌중에까지 침입하여 사람들을 다 내어몰고 방 안, 부엌, 벽장 할 것 없이 온통 점령을 하고 말았다

In [19]:
twitter = Komoran(userdic='./user_dic.txt')
# twitter = Okt()

In [20]:
#형태소분석
sentences_tag = []
for sentence in sent:
    morph = twitter.pos(sentence)
    sentences_tag.append(morph)

In [21]:
print(sentences_tag[0])

[('이광수', 'NNP'), ('<', 'SS'), ('무정', 'NNP'), ('>', 'SS'), ('1', 'SN'), ('경성', 'NNP'), ('학교', 'NNP'), ('영어', 'NNP'), ('교사', 'NNG'), ('이', 'MM'), ('형식', 'NNP'), ('은', 'JX'), ('오후', 'NNG'), ('두', 'MM'), ('시', 'NNB'), ('사', 'NR'), ('년', 'NNB'), ('급', 'NNG'), ('영어', 'NNP'), ('시간', 'NNG'), ('을', 'JKO'), ('마치', 'VV'), ('고', 'EC'), ('내리', 'VV'), ('어', 'EC'), ('쪼이', 'VV'), ('는', 'ETM'), ('유월', 'NNP'), ('볕', 'NNG'), ('에', 'JKB'), ('땀', 'NNG'), ('을', 'JKO'), ('흘리', 'VV'), ('면서', 'EC'), ('안동', 'NNP'), ('김', 'NNP'), ('장로', 'NNP'), ('의', 'JKG'), ('집으로 간다', 'NNP'), ('.', 'SF'), ('김', 'NNP'), ('장로', 'NNP'), ('의', 'JKG'), ('딸', 'NNG'), ('선형', 'NNP'), ('(', 'SS'), ('善馨', 'SH'), (')', 'SS'), ('이', 'NP'), ('가', 'JKS'), ('명년', 'NNG'), ('미국', 'NNP'), ('유학', 'NNG'), ('을', 'JKO'), ('가', 'VV'), ('기', 'ETN'), ('위하', 'VV'), ('아', 'EC'), ('영어', 'NNP'), ('를', 'JKO'), ('준비', 'NNG'), ('하', 'XSV'), ('ㄹ', 'ETM'), ('차로', 'NNP'), ('이', 'MM'), ('형식', 'NNP'), ('을', 'JKO'), ('매일', 'MAG'), ('한', 'MM'), ('시간', 'NNG'), ('씩', 

In [22]:
#명사 추출
noun_adj=[]

#komoran
# for sentence1 in sentences_tag:
#     for word, tag in sentence1:
#         if tag in ['NNP']: 
#             noun_adj.append(word)

#twitter
for sentence1 in sentences_tag:
    for word, tag in sentence1:
        if word=='왕' or len(word)>1:
#             pass
#         if len(word)>1:
            if tag in ['NNP']: #komoran
                noun_adj.append(word)

In [23]:
print(noun_adj)

'바가', '그네', '이희경', '이희경', '형식', '너는', '빙그레', '모욕', '형식', '형식', '네야', '리나', '조선', '형식', '말로', '사권', '문법', '관계', '영어', '중학교', '박사', '중학교', '중학교', '이희경', '급부', '진보', '그네', '양이', '양이', '이언', '와서', '전과', '양이', '형식', '양이', '그네', '조선', '조선', '교만', '서양 철학', '루소', '참회록', '에밀', '셰익스피어', '햄릿', '괴테', '파우스트', '약탈', '평론', '일본', '잡지', '상도', '타고르', '엘렌 케이', '전기', '인생관', '만원', '열도', '조선', '문명', '조선', '자라', '조선', '파만', '조선', '서울', '조선인', '산술', '일어', '조선인', '경성', '선전', '형식', '바가', '영어', '직역', '그네', '사람의 마음', '사람의 마음', '간의', '바가', '적도', '적도', '그네', '차차', '철학자', '별명', '너는', '철학자', '별명', '궐련', '분필', '통과', '빙글빙글', '김종', '책상', '암만', '해도', '김구', '책상', '일동', '연필', '모욕', '웃음', '이오', '일동', '연필', '선생님', '질문', '선생님', '제가', '일동', '평양', '평양', '가시', '누가', '계월향', '후후', '선생', '계월향', '가오', '눈에는 눈', '물이', '궐련', '평양', '아마', '재미', '평양', '선생님', '계월향', '선생', '계월향', '허허', '이기', '인지', '이로', '구려', '형식', '유하', '관보', '백이', '숙제', '편자', '체조', '수건', '이마', '체조', '다시', '자로', '철봉', '포플러', '형식', '포플러', '포플러', '안동', '일기', '파출소', '추녀', '후후

In [86]:
############# TF-IDF###################

In [24]:
vector = CountVectorizer()
print(vector.fit_transform(noun_adj).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
{'이광수': 1110, '무정': 485, '경성': 69, '학교': 1570, '영어': 1001, '형식': 1624, '유월': 1082, '안동': 913, '장로': 1219, '집으로': 1398, '간다': 24, '선형': 742, '미국': 498, '차로': 1401, '가정교사': 19, '빙하': 650, '세시': 762, '독신': 334, '처음': 1420, '자라': 1185, '이마': 1126, '책상': 1417, '점심': 1267, '불어': 625, '코로': 1482, '전신': 1259, '미스터': 502, '놀라': 275, '신우선': 864, '오래': 1013, '허교': 1603, '하기': 1548, '맥주': 440, '사나이': 657, '파출소': 1513, '청국': 1445, '오늘': 1012, '부신': 598, '여자': 966, '오메': 1016, '하네': 1553, '나루': 222, '호도': 1631, '라고': 376, '정신여학교': 1277, '베리': 554, '시쿠': 845, '미인': 504, '교동': 122, '황금시대': 1650, '황금': 1649, '남이': 242, '예수': 1007, '아이들': 899, '목사': 475, '집사': 1397, '사찰': 690, '시체': 842, '김광현': 204, '대문': 315, '사도': 659, '연마': 975, '개명': 50, '하면': 1561, '하인': 1563, '김장': 209, '서울': 723, '교회': 130, '이리': 1125, '대청': 318, '리가': 393, '양식': 931, '유리': 1075, '문도': 490, '테이블': 1498, '신구': 85

In [12]:
# tfidfv = TfidfVectorizer().fit(noun_adj)
# print(tfidfv.transform(noun_adj).toarray())
# print(type(tfidfv.vocabulary_.items()))

In [25]:
# TF-IDF 설정
tfidf = TfidfVectorizer(max_features = 10, max_df=0.95, min_df=0) #(max_features = 5) <- 상위 5개만 추출

#generate tf-idf term-document matrix
A_tfidf_sp = tfidf.fit_transform(noun_adj)

In [26]:
tfidf_dict = tfidf.get_feature_names()
print(tfidf_dict)

['그네', '기생', '미국', '선형', '월화', '장로', '조선', '채의', '평양', '형식']


In [15]:
from itertools import combinations
test = list(combinations(tfidf_dict, 2))

In [16]:
#############Word2Vec######################

In [17]:
sents = [doc.split(" ") for doc in noun_adj] #Word2Vec 을 위한 전처리

In [18]:
model = word2vec.Word2Vec(sents, size=200,window=100,hs=1,min_count=2,sg=1)

print(list(model.wv.vocab.keys()))
print("vocab length : %d"%len(model.wv.vocab))

['무정', '경성', '학교', '영어', '형식', '유월', '안동', '장로', '집으로', '간다', '선형', '미국', '차로', '빙하', '세시', '자라', '이마', '책상', '점심', '불어', '코로', '전신', '놀라', '신우선', '오래', '허교', '하기', '맥주', '사나이', '파출소', '청국', '오늘', '부신', '여자', '하네', '라고', '미인', '교동', '황금', '남이', '예수', '아이들', '목사', '시체', '대문', '사도', '연마', '하면', '하인', '김장', '서울', '교회', '이리', '대청', '리가', '양식', '유리', '테이블', '신구', '서적', '구두', '로라', '매우', '화채', '연해', '말하자면', '너는', '이어', '제가', '마님', '아씨', '모시', '적삼', '치마', '애가', '이도', '은혜', '눈썹', '기름', '바른', '오리', '고운', '무릎', '손은', '평양', '춘향', '별명', '양반', '기생', '후회', '하나', '버림', '청년', '전과', '순애', '이애', '동정', '이전', '아주', '오마', '하리', '공책', '드릴', '연필', '기로', '기가', '선생님', '삼사', '객주', '선생', '서서', '양이', '아가씨', '마루', '게로', '구려', '에그', '암만', '해도', '김선형', '저고리', '여자도', '광명', '램프', '담요', '눈에는', '눈', '물이', '데리', '고', '온', '비창', '유여', '박진', '사라', '안주', '신미', '진사', '일본', '조선', '모아', '철도', '평안도', '인해', '사가', '산술', '일어', '사위', '채의', '소학', '열녀전', '정다운', '성력', '방책', '사방', '옆구리', '칼로', '현금', '중도', '강도', '살인', '부자', '남은', '그', '

In [19]:
wv = model.wv #Word2Vec model
# del(model)
# 전달받은 sigwords 중 model에 포함된 단어를 우선순위 순서로 추려냄
sigvocs = []
missvocs = []
hit = 0
miss = 0
for worddic in tfidf_dict:
    try:
        word = worddic
        if wv.vocab[word]:
            sigvocs.append(word)
            hit += 1
        if hit >= length:
            break
    except:
        missvocs.append(word)
        miss += 1
# 디버깅용. 추후 삭제.
print("missed: %d"  % miss)
for voc in missvocs:
    print(voc)


# 디스턴스 매트릭스를 데이터프레임 형태로 만듦
distDF =  pandas.DataFrame(columns = sigvocs , index = sigvocs)
for i in sigvocs:
    dists = []
    for j in sigvocs:
        dist = round(wv.distance(i, j), 6)
        dists.append(0 if dist < 1.0e-2 else dist)
    distDF[i] = dists
print(distDF)

missed: 10
그네
기생
미국
선형
월화
장로
조선
채의
평양
형식
          그네        기생        미국        선형        월화        장로        조선  \
그네  0.000000  0.955793  1.081989  1.023512  1.093576  0.949063  1.087554   
기생  0.955793  0.000000  0.827477  1.093738  0.972771  0.797748  0.872108   
미국  1.081989  0.827477  0.000000  1.029086  0.953648  0.946901  0.915714   
선형  1.023512  1.093738  1.029086  0.000000  1.058699  1.055182  1.103228   
월화  1.093576  0.972771  0.953648  1.058699  0.000000  0.937254  1.069553   
장로  0.949063  0.797748  0.946901  1.055182  0.937254  0.000000  1.080106   
조선  1.087554  0.872108  0.915714  1.103228  1.069553  1.080106  0.000000   
채의  0.884449  0.865556  0.960653  1.132819  1.082094  0.980047  0.954981   
평양  0.957374  0.836905  1.031282  1.003441  0.977946  0.883620  1.016126   
형식  1.032598  1.056362  0.946404  1.018800  0.942196  0.899053  0.912018   

          채의        평양        형식  
그네  0.884449  0.957374  1.032598  
기생  0.865556  0.836905  1.056362  
미국  0.960653  1.0

In [20]:
print(distDF)

그네        기생        미국        선형        월화        장로        조선  \
그네  0.000000  0.955793  1.081989  1.023512  1.093576  0.949063  1.087554   
기생  0.955793  0.000000  0.827477  1.093738  0.972771  0.797748  0.872108   
미국  1.081989  0.827477  0.000000  1.029086  0.953648  0.946901  0.915714   
선형  1.023512  1.093738  1.029086  0.000000  1.058699  1.055182  1.103228   
월화  1.093576  0.972771  0.953648  1.058699  0.000000  0.937254  1.069553   
장로  0.949063  0.797748  0.946901  1.055182  0.937254  0.000000  1.080106   
조선  1.087554  0.872108  0.915714  1.103228  1.069553  1.080106  0.000000   
채의  0.884449  0.865556  0.960653  1.132819  1.082094  0.980047  0.954981   
평양  0.957374  0.836905  1.031282  1.003441  0.977946  0.883620  1.016126   
형식  1.032598  1.056362  0.946404  1.018800  0.942196  0.899053  0.912018   

          채의        평양        형식  
그네  0.884449  0.957374  1.032598  
기생  0.865556  0.836905  1.056362  
미국  0.960653  1.031282  0.946404  
선형  1.132819  1.003441  1.018800 

In [163]:
for i in tfidf_dict:
    print(i)
    print(wv.most_similar(positive=i, negative=[]))

가로등
[('램프', 0.1519162803888321), ('지도', 0.1507382094860077), ('바오밥', 0.14544129371643066), ('스물', 0.13423864543437958), ('않았다', 0.12449805438518524), ('마리', 0.11994068324565887), ('별', 0.11088405549526215), ('말라', 0.10797130316495895), ('하면', 0.10207945108413696), ('은', 0.09872396290302277)]
나무
[('정원', 0.20593084394931793), ('버섯', 0.15435954928398132), ('해서', 0.15244406461715698), ('지구', 0.13618254661560059), ('앞으로', 0.1319880336523056), ('램프', 0.1304701566696167), ('사형', 0.12845274806022644), ('모래', 0.1283337026834488), ('도르래', 0.12784849107265472), ('에다', 0.1195182204246521)]
바오밥
[('하지', 0.2197958528995514), ('않았다', 0.20339716970920563), ('왕이', 0.1803896278142929), ('아침', 0.1717682182788849), ('급행열차', 0.1596197485923767), ('빛으로', 0.15780289471149445), ('비행기', 0.14777915179729462), ('가로등', 0.14544129371643066), ('오늘', 0.13850843906402588), ('양의', 0.13778156042099)]
송이
[('한', 0.17684802412986755), ('지도', 0.17412157356739044), ('담비', 0.12356951832771301), ('왕자', 0.10470542311668396), ('

In [164]:
print((test))

[('가로등', '나무'), ('가로등', '바오밥'), ('가로등', '송이'), ('가로등', '아저씨'), ('가로등', '어린'), ('가로등', '여우'), ('가로등', '왕이'), ('가로등', '왕자'), ('가로등', '화산'), ('나무', '바오밥'), ('나무', '송이'), ('나무', '아저씨'), ('나무', '어린'), ('나무', '여우'), ('나무', '왕이'), ('나무', '왕자'), ('나무', '화산'), ('바오밥', '송이'), ('바오밥', '아저씨'), ('바오밥', '어린'), ('바오밥', '여우'), ('바오밥', '왕이'), ('바오밥', '왕자'), ('바오밥', '화산'), ('송이', '아저씨'), ('송이', '어린'), ('송이', '여우'), ('송이', '왕이'), ('송이', '왕자'), ('송이', '화산'), ('아저씨', '어린'), ('아저씨', '여우'), ('아저씨', '왕이'), ('아저씨', '왕자'), ('아저씨', '화산'), ('어린', '여우'), ('어린', '왕이'), ('어린', '왕자'), ('어린', '화산'), ('여우', '왕이'), ('여우', '왕자'), ('여우', '화산'), ('왕이', '왕자'), ('왕이', '화산'), ('왕자', '화산')]


In [165]:
for i in test:
    i = str(i)
    i = i.replace("(","").replace(")","").replace("'","").replace(" ","").split(",")
    print((i))
    print(wv.most_similar(positive=i, negative=[]))

['가로등', '나무']
[('램프', 0.20159554481506348), ('버섯', 0.1581709384918213), ('사형', 0.14358098804950714), ('않았다', 0.14170455932617188), ('증거', 0.14084208011627197), ('은', 0.1367659717798233), ('정원', 0.1328253448009491), ('구렁이', 0.1307421177625656), ('양의', 0.1306142508983612), ('지도', 0.12047120928764343)]
['가로등', '바오밥']
[('않았다', 0.2166375368833542), ('램프', 0.1800018846988678), ('하지', 0.16752615571022034), ('왕이', 0.1606503129005432), ('지도', 0.1563330888748169), ('아침', 0.1509913206100464), ('말라', 0.14397308230400085), ('양의', 0.13401752710342407), ('빛으로', 0.12371589988470078), ('비행기', 0.11206663399934769)]
['가로등', '송이']
[('지도', 0.22497829794883728), ('마리', 0.15271934866905212), ('스물', 0.13218513131141663), ('아저씨', 0.11728544533252716), ('한', 0.11594505608081818), ('목이', 0.11084188520908356), ('왕자', 0.10643582046031952), ('말라', 0.10249060392379761), ('우물', 0.09508798271417618), ('별', 0.09317779541015625)]
['가로등', '아저씨']
[('램프', 0.1808968037366867), ('상자', 0.13939447700977325), ('지리학', 0.13703705

In [ ]:
############################################

In [0]:
import re
import json

from pprint import pprint


###########감정 분석############
#sentifile = open('C:/Users/student/Documents/GitHub/Moons/분석/test3.txt','r',encoding='utf-8')
sentifile = open('C:/Users/student/Documents/GitHub/Moons/분석/test3.txt','r',encoding='utf-8')
senti_line = sentifile.readlines() #한 문장씩 받기


##### 함수 모음 #######

def sum_list(list_inform):
    res=0
    for i in list_inform:      
        res += i
    return res 


#### 입력받은 사람이 들어간 문장 차기위한 변수 생성 #####
character_senti = [['형식'],['영채'],['병욱'],['선형']] 

result = []
for i in character_senti[0:]:
    B=character_senti.pop(0)
    result += ([B+a for a in character_senti])

#print(result)

##### 한 문장에 캐릭터 2명이 들어간 것을 찾는다. #####
##### match_char 리스트 안에 넣어준다. #####

match_char=[]
for i in result:
    i = str(i) 
    #b = ' '
    for sents in senti_line[0:]:
        
        #b.append(i.[0]+" "+i.[1])

        p=re.compile('형식|영채')
        m = p.findall(sents) 
        
        if m[0:] == ['형식','영채']:
            match_char.append(sents)
        elif i == ['형식','병욱']:
            break

##### KNU 감성 사전을 통해서 감정 분석 #####


#감정 사전함수#
class KnuSL():

#감정 사전함수
    def data_list(wordname):

        with open('C:/Users/student/Documents/GitHub/Moons/분석/data/SentiWord_info.json', encoding='utf-8-sig', mode='r') as f:
            data = json.load(f)

        result = ['None','None']	
        for i in range(0, len(data)):
            if data[i]['word'] == wordname:
                result.pop()
                result.pop()
                result.append(data[i]['word_root'])
                result.append(data[i]['polarity'])	

        r_word = result[0]
        s_word = result[1]

        return r_word, s_word

#감정분성 메인
pre_sents=[]
for stuff in match_char[0:]:
    stuff= "\n".join([s for s in stuff.split("\n") if s])
    pre_sents.append(stuff)

komoran_words=[]
for sents in pre_sents:
    match_pos_cahr = twitter.pos(sents)
    
    for word, tag in match_pos_cahr:
        komoran_words.append(word)
        

if __name__ == "__main__":

    ksl = KnuSL
    count = 0
    
    
    for i in komoran_words:

        count += 1
        if count==106:
            break

        #print(i)
        #i = i.strip(" ")
        point = ksl.data_list(i)
        #print(point)
        # print(point[1])

        #print(point[1][0:])
        count = count+1
        try:
            
            result_sum = 0
            for score in point[1::2]:
                         
                #print(score)
                a = int(score)

                
                #print(a)
                result_sum += a 
                
                #result_sum.append(a)
                
                #print(type(score))a
            # print(i)    
            #sum(result_sum)
             
            #print(result_sum)
            
        except ValueError:
            continue
    print(result_sum)

# for i in character_senti[0:]:
                # if score == Number:
                #     senti_score += score
                # else:
                #     continue

        #print(senti_score)
    #print("값은 ", sum(result_sum))   
# a = sum(result_sum)
# print("값은" , a)
# print("값은" , sum_list(result_sum))

# final_result = sum(result_sum)
# print(final_result)       

#print(result)


In [38]:
################################
a='1'
int(a)
print(a)

1


In [ ]:
import pandas as pd
pd.options.mode.chained_assignment = None

import numpy as np
np.random.seed(0)

from konlpy.tag import Twitter
twitter = Twitter()

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from sklearn.feature_extraction.text import HashingVectorizer

In [ ]:
def tokenizer(raw, pos=["Noun","Alpha","Verb","Number"], stopword=[]):
    return [
        word for word, tag in twitter.pos(
            raw, 
            norm=True,   # normalize 그랰ㅋㅋ -> 그래ㅋㅋ
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

In [ ]:

file = open('./TheLittlePrince.txt','r',encoding='utf-8')
raw_lines = file.readlines()

# 2. 변수 rawdata 저장
rawdata = []
for line in raw_lines:
    rawdata.append(line)

In [85]:
print(rawdata)

['\ufeff여섯 살 적에 나는 "체험한 이야기"라는 제목의, 원시림에 관한 책에서 기막힌 그림 하나를 본 적이 있다. 맹수를 집어삼키고 있는 보아 구렁이 그림이었다. 위의 그림은 그것을 옮겨 그린 것이다.\n', ' 그 책에는 이렇게 씌어 있었다.\n', ' "보아 구렁이는 먹이를 씹지도 않고 통째로 집어삼킨다.그리고는 꼼짝도 하지 못하고 여섯 달 동안 잠을 자면서 그것을 소화시킨다."\n', ' 나는 그래서 밀림 속에서의 모험에 대해 한참 생각해 보고 난 끝에 색연필을 가지고 내 나름대로 내 생애 첫번째 그림을 그려보았다. 나의 그림 제 1호였다. 그것은 이런 그림이었다.\n', ' 나는 그 걸작품을 어른들에게 보여 주면서내 그림이 무섭지 않느냐고 물었다.\n', ' 그들은 "모자가 뭐가 무섭다는 거니?" 하고 대답했다.\n', ' 내 그림은 모자를 그린 게 아니었다. 그것은 코끼리를 소화시키고 있는 보아 구렁이었다.\n', ' 그래서 나는 어른들이 알아볼 수 있도록 보아 구렁이의 속을 그렸다. 어른들은 언제나 설명을 해주어야만 한다. 나의 그림 제 2호는 이러했다.\n', ' 어른들은 속이 보이거나 보이지 않거나 하는 보아 구렁이의 그림들은 집어치우고 차라리 지리, 역사, 계산, 그리고 문법 쪽에 관심을 가져보는 게 좋을 것이라고 충고해 주었다.\n', ' 그래서 나는 여섯 살 적에 화가라는 멋진 직업을 포기해 버렸다.내 그림제 1호와 제 2호가 성공을 거두지 못한 데 낙심해 버렸던 것이다. 어른들은언제나 스스로는 아무것도 이해하지 못한다.자꾸자꾸 설명을 해주어야 하니 맥빠지는 노릇이 아닐 수 없다.\n', ' 그래서 다른 직업을 선택하지 않을 수 없게 된 나는 비행기 조종하는 법을배웠다.세계의 여기저기 거의 안 가본 데 없이 나는 날아다녔다.그러니지리는 정말로 많은 도움을 준 셈이었다.한번 슬쩍 보고도 중국과 애리조나를 나는 구별할 수 있었던 것이다.그것은 밤에 길을 잃었을 때 아주 유용한 일이다.\n', ' 나는 그리하여 일생 동안 수없이 많은 점잖

In [86]:
vectorize = HashingVectorizer(
    tokenizer=tokenizer,
    n_features=7               # 기본 feature 수를 설정하며 기본값이 2의 20승이다. 아래 예시를 위해 feature 를 7로 한정했으나, 아래 유사문장을 찾을때는 다시 n_features 주석처리 했다.
)
X = vectorize.fit_transform(rawdata)
 
print(X.shape)
 
print(X.toarray())

(977, 7)
[[-0.26726124 -0.26726124  0.26726124 ...  0.         -0.26726124
   0.80178373]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.37796447 -0.75592895  0.         ...  0.          0.
   0.37796447]
 ...
 [ 0.51639778  0.51639778  0.         ... -0.25819889 -0.25819889
  -0.51639778]
 [-0.12216944  0.85518611  0.24433889 ...  0.24433889 -0.24433889
   0.12216944]
 [ 0.          0.52075564  0.13018891 ... -0.52075564 -0.13018891
  -0.39056673]]


In [89]:

# search 문장 벡터
srch_vector = vectorize.transform([
    '왕자 여우'
])
 
print(srch_vector.shape)
# (1, 7)


(1, 7)


In [90]:
from sklearn.metrics.pairwise import linear_kernel
 
# linear_kernel는 두 벡터의 dot product 이다.
cosine_similar = linear_kernel(srch_vector, X).flatten()
# cosine_similar = (srch_vector*X.T).toarray().flatten()
 
print(cosine_similar)
# [0.         0.         0.62017367 0.31622777 0.3]
 
print(cosine_similar.shape)
# (5,)
 
# 유사한 rawdata index
sim_rank_idx = cosine_similar.argsort()[::-1]
print(sim_rank_idx)
#[2 3 4 1 0]
 
for i in sim_rank_idx:
    if cosine_similar[i] > 0:
        print('{} / score : {}'.format(rawdata[i], cosine_similar[i]))

[-0.37796447 -0.70710678  0.         -0.5        -0.42640143  0.5
 -0.35355339  0.         -0.12700013 -0.34815531  0.45226702  0.20412415
  0.0521286   0.          0.          0.46291005 -0.19611614  0.
 -0.5        -0.70710678 -0.5         0.10783277  0.          0.
  0.         -0.40824829  0.53452248 -0.19781414 -0.5        -0.23249528
  0.         -0.35355339 -0.70710678 -0.70710678  0.35355339 -0.40824829
 -0.8660254   0.81649658  0.54772256  0.          0.          0.
  0.70710678  0.          0.          0.          0.          0.35355339
  0.          0.33333333  0.70710678  0.67082039 -0.28867513  0.
  0.5         0.         -0.35355339  0.          0.          0.
  0.          0.63245553  0.         -0.67082039 -0.42640143  0.
  0.5         0.          0.          0.23570226  0.40824829  0.28867513
  0.40824829  0.          0.5         0.40824829  0.         -0.70710678
  0.40824829  0.          0.45291081  0.         -0.25       -0.15811388
  0.          0.          0.     

In [66]:
###################################연관분석

In [67]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [68]:
import numpy as np
import pandas as pd
from apyori import apriori

In [56]:
association_rules = apriori(sentences_tag,min_support=0.0053, min_confidence=0.20, min_lift=3, min_length=2)

In [ ]:
######### 낙서장 ########
##### 한 문장에 캐릭터 2명이 들어간 것을 찾는다 #####

match_char=[]
for i in result:
    #print(i)
    i = str(i) 
 
    # i.replace("[","").replace("]","").replace(",","")

    # print(b)
    #print(type(i)) #= str
    for sents in senti_line[0:]:
        #print(type(sents))
        # sents = str(sents)
        p=re.compile('형식|영희+')
        #print(type(sents))
        #b = sents.preprocessing()
        #sents = twitter.nouns(b)
        #print(type(sents))
        #p = re.compile("^형식\s\w+",re.MULTILINE)
        #print(i)
        #print(sents)
        m = p.findall(sents) 
        print(m)
        