In [21]:
from collections import Counter
from konlpy.utils import pprint
from konlpy.tag import Twitter
from konlpy.tag import Komoran
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

In [22]:
import re

#파일 읽어오기
file = open('C:/Users/student/Documents/GitHub/Moons/분석/test3.txt','r',encoding='utf-8')
line = file.read()

#장(chapter)마다 나눔
sentences = re.split('(?<=[2-9]\n)|(?<=[0-9][0-9]\n)|(?<=[0-9][0-9][0-9]\n)', line)

#Komoran 형태소 분석을 위한 전처리
sent=[]
for stuff in sentences:
#         stuff = stuff.replace("'","").replace("?","").replace(".","").replace("'","").replace('"'
# ,"").replace("!","").replace("-","").replace('"',"").replace("\n","")
        # stuff = re.sub("\n","", line).strip()
        stuff= "\n".join([s for s in stuff.split("\n") if s])
        sent.append(stuff)

In [23]:
print(sent[20])

형식은 분해하는 김종렬을 향하여,
“그러나 그런 온당치 못한 일을 해서야 쓰겠나. 참아야지.”
“아니올시다. 벌써 삼 년 동안이나 참았습니다” 하고 기어이 배학감을 배척하고야 말려 한다. 김종렬은 말을 이어,
“이렇게 이백여 명 용감한 청년들이 동맹을 체결하였는데 이제는 일보도 양보할 수가 없습니다.”
“그러나 교주께서 허하지 아니하시면 할 수 있소?”
김종렬은 ‘교주’란 말을 듣고 얼마큼 낙심하였다. 한참 고개를 기웃기웃하고 생각하더니,
“그러니까 퇴학합지요. 경성학교가 아니면 학교가 없어요?”
“그러나 아무리 고식한 일이 있어도 동맹 퇴학은 온당치 아니하시. 또 모교를 떠나기가 어렵지 아니한가?”
“모교가 무슨 모교오니까. 이전 박선생님께서 교장으로 계시고, 윤선생님께서 학감으로 계실 때에는 모교였지마는…… 지금은 학교에 대하여 정이란 조곰도 없습니다. 교장이라는 어른은 아무것도 모르시지요…… 학감이라는 자는 기생집에만 다니지요……” 하고 김종렬의 눈에는 분한 기운이 오른다. 이희경은 ‘학감이란 자’라는 말을 듣고 김의 옆을 찌르며,
“여보, 그게 무슨 말이오?”
“어째! 그따위 학감을 무어라고!”
형식은 근심하는 빛으로,
“그러면 지금 교장 댁으로 가려 하오?”
“녜, 교장어른 가 뵈옵고, 열점쯤 해서 교주 댁으로 가렵니다. 교주는 열점이나 되어야 일어난다니까…… 그런데 선생님께서는 저희 일에 동정하십니까?”
“내가 교사의 몸이 되어 동정하고 말고를 말할 수가 없지마는 다시 생각하여서 일이 없도록 하여야지” 하고 두 청년을 돌려보냈다. 형식도 마음으로는 무론 배학감의 배척에 찬성하였다. 교실에서 무슨 말하던 끝에 혹 그 비슷한 말을 한두 번 한 적도 있었다. 사백여 명 학생과 십여 명 교원 중에 배를 좋아하는 사람은 오직 하나도 없었다. 교원들도 아무쪼록 배학감과 말을 아니하려 하고 학생들도 길가에서 만나면 못 본 체하고 지나간다. 누군지 모르나 익명으로 배학감에게 학감 사직의 권고를 한 자도 있고, 혹 배학감이 맡은 역사나 지리 시간에 칠판에다가 ‘배학

In [24]:
twitter = Komoran(userdic='./user_dic.txt')
#twitter = Komoran()

In [25]:
#형태소분석
sentences_tag = []
for sentence in sent:
    morph = twitter.pos(sentence)
    sentences_tag.append(morph)

In [26]:
print(sentences_tag[0])

[('이광수', 'NNP'), ('<', 'SS'), ('무정', 'NNP'), ('>', 'SS'), ('1', 'SN'), ('경성', 'NNP'), ('학교', 'NNP'), ('영어', 'NNP'), ('교사', 'NNG'), ('이', 'MM'), ('형식', 'NNP'), ('은', 'JX'), ('오후', 'NNG'), ('두', 'MM'), ('시', 'NNB'), ('사', 'NR'), ('년', 'NNB'), ('급', 'NNG'), ('영어', 'NNP'), ('시간', 'NNG'), ('을', 'JKO'), ('마치', 'VV'), ('고', 'EC'), ('내리', 'VV'), ('어', 'EC'), ('쪼이', 'VV'), ('는', 'ETM'), ('유월', 'NNP'), ('볕', 'NNG'), ('에', 'JKB'), ('땀', 'NNG'), ('을', 'JKO'), ('흘리', 'VV'), ('면서', 'EC'), ('안동', 'NNP'), ('김', 'NNP'), ('장로', 'NNP'), ('의', 'JKG'), ('집으로 간다', 'NNP'), ('.', 'SF'), ('김', 'NNP'), ('장로', 'NNP'), ('의', 'JKG'), ('딸', 'NNG'), ('선형', 'NNP'), ('(', 'SS'), ('善馨', 'SH'), (')', 'SS'), ('이', 'NP'), ('가', 'JKS'), ('명년', 'NNG'), ('미국', 'NNP'), ('유학', 'NNG'), ('을', 'JKO'), ('가', 'VV'), ('기', 'ETN'), ('위하', 'VV'), ('아', 'EC'), ('영어', 'NNP'), ('를', 'JKO'), ('준비', 'NNG'), ('하', 'XSV'), ('ㄹ', 'ETM'), ('차로', 'NNP'), ('이', 'MM'), ('형식', 'NNP'), ('을', 'JKO'), ('매일', 'MAG'), ('한', 'MM'), ('시간', 'NNG'), ('씩', 

In [28]:
#명사 추출
noun_adj=[]

#komoran
# for sentence1 in sentences_tag:
#     for word, tag in sentence1:
#         if tag in ['NNP']: 
#             noun_adj.append(word)

#twitter
for sentence1 in sentences_tag:
    for word, tag in sentence1:
        if tag in ['NNP']: #komoran
            noun_adj.append(word)

print(noun_adj)

'잎새', '이', '풍금', '형식', '목사', '장로', '승낙', '장로', '허허', '장로', '사시', '오마', '분이', '장로', '사랑하니까', '제가', '장로', '승낙', '암만', '해도', '장로', '승낙', '장로', '하', '차고', '김', '장로', '이오', '오래', '목사', '당자', '선형', '목사', '장로', '테이블', '마님', '아씨', '소사', '하인', '그네', '그네', '선형', '선형', '영어', '전신', '선형', '선형', '선형', '손수건', '이마', '장로', '선형', '목사', '선형', '형식', '이', '장로', '이', '선생', '선형', '선형', '형식', '이', '형식', '이', '정다운', '순애', '순애', '할라', '순애', '양도', '선생', '이', '선생', '순애', '선생', '순애', '선형', '순애', '이', '이', '선생', '어머님께', '선형', '선생', '사람의 마음', '에그', '어쩌면 좋아', '회화', '선형', '악인', '천한', '러', '한', '선형', '형식', '이', '정다운', '정다운', '선형', '이', '선형', '이', '형식', '이', '선형', '조', '선형', '선형', '김장', '양주', '목사', '그네', '천', '켤레', '장로', '선형', '장로', '목사', '위선', '무릎', '목사', '차차', '무소', '우리 주', '여호와', '지각', '우리 주', '만세', '정해', '형식', '박', '선형', '약혼', '비둘기', '리라', '여호와', '비오리', '십자가', '구주', '예수', '그리스도', '아멘', '목사', '아멘', '목사', '장로', '양주', '선형', '장로', '약혼', '승낙', '장로', '이로', '구려', '약혼', '목사', '당자', '장로', '당자', '장로', '당자', '선형', '목사', '장로', 

In [9]:
############# TF-IDF###################

In [29]:
import pandas as pd
from collections import Counter
from sklearn.manifold import TSNE
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
vector = CountVectorizer()
print(vector)
print(vector.fit_transform(noun_adj).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
{'이광수': 1110, '무정': 485, '경성': 69, '학교': 1570, '영어': 1001, '형식': 1624, '유월': 1082, '안동': 913, '장로': 1219, '집으로': 1398, '간다': 24, '선형': 742, '미국': 498, '차로': 1401, '가정교사': 19, '빙하': 650, '세시': 762, '독신': 334, '처음': 1420, '자라': 1185, '이마': 1126, '책상': 1417, '점심': 1267, '불어': 625, '코로': 1482, '전신': 1259, '미스터': 502, '놀라': 275, '신우선': 864, '오래': 1013, '허교': 1603, '하기': 1548, '맥주': 440, '사나이': 657, '파출소': 1513, '청국': 1445, '오늘': 1012, '부신': 598, '여자': 966, '오메': 101

In [31]:
tfidfv = TfidfVectorizer().fit(noun_adj)
print(tfidfv.transform(noun_adj).toarray())
print(tfidfv.vocabulary_)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
{'이광수': 1110, '무정': 485, '경성': 69, '학교': 1570, '영어': 1001, '형식': 1624, '유월': 1082, '안동': 913, '장로': 1219, '집으로': 1398, '간다': 24, '선형': 742, '미국': 498, '차로': 1401, '가정교사': 19, '빙하': 650, '세시': 762, '독신': 334, '처음': 1420, '자라': 1185, '이마': 1126, '책상': 1417, '점심': 1267, '불어': 625, '코로': 1482, '전신': 1259, '미스터': 502, '놀라': 275, '신우선': 864, '오래': 1013, '허교': 1603, '하기': 1548, '맥주': 440, '사나이': 657, '파출소': 1513, '청국': 1445, '오늘': 1012, '부신': 598, '여자': 966, '오메': 1016, '하네': 1553, '나루': 222, '호도': 1631, '라고': 376, '정신여학교': 1277, '베리': 554, '시쿠': 845, '미인': 504, '교동': 122, '황금시대': 1650, '황금': 1649, '남이': 242, '예수': 1007, '아이들': 899, '목사': 475, '집사': 1397, '사찰': 690, '시체': 842, '김광현': 204, '대문': 315, '사도': 659, '연마': 975, '개명': 50, '하면': 1561, '하인': 1563, '김장': 209, '서울': 723, '교회': 130, '이리': 1125, '대청': 318, '리가': 393, '양식': 931, '유리': 10

In [36]:
# TF-IDF 설정
tfidf = TfidfVectorizer(max_features = 100, max_df=0.95, min_df=0) #(max_features = 5) <- 상위 5개만 추출

#generate tf-idf term-document matrix
A_tfidf_sp = tfidf.fit_transform(noun_adj)

In [37]:
tfidf_dict = tfidf.get_feature_names()
character = ['형식','영채','병욱','선형']
result=[]
for twit_name in tfidf_dict:
    for name in character:
        if name == twit_name:
            result.append(name)
        else:
            continue

print(result)
# print(type(result))

['선형', '형식']


In [13]:
#############Word2Vec######################

In [14]:
sents = [doc.split(" ") for doc in result] #Word2Vec 을 위한 전처리

In [21]:
from gensim.models import word2vec

model = word2vec.Word2Vec(sents,size=200,window=10,hs=1,min_count=1,sg=1)

print(list(model.wv.vocab.keys()))
print("vocab length : %d" % len(model.wv.vocab))

print(model.wv.most_similar("영채"))

['선형', '영채', '형식']
vocab length : 3
[('선형', 0.07835608720779419), ('형식', -0.02377626858651638)]


In [22]:
from gensim.models import Word2Vec
import pandas

In [23]:
wv = model.wv #Word2Vec model
# del(model)
# 전달받은 sigwords 중 model에 포함된 단어를 우선순위 순서로 추려냄
sigvocs = []
missvocs = []
hit = 0
miss = 0
for worddic in tfidf_dict:
    try:
        word = worddic
        if wv.vocab[word]:
            sigvocs.append(word)
            hit += 1
        if hit >= length:
            break
    except:
        missvocs.append(word)
        miss += 1
# 디버깅용. 추후 삭제.
print("missed: %d"  % miss)
for voc in missvocs:
    print(voc)


# 디스턴스 매트릭스를 데이터프레임 형태로 만듦
distDF =  pandas.DataFrame(columns = sigvocs , index = sigvocs)
for i in sigvocs:
    dists = []
    for j in sigvocs:
        dist = round(wv.distance(i, j), 6)
        dists.append(0 if dist < 1.0e-2 else dist)
    distDF[i] = dists
print(distDF)

missed: 8
노파
사람
생각
선형
얼굴
영채
자기
형식
          선형        영채        형식
선형  0.000000  0.921644  1.109971
영채  0.921644  0.000000  1.023776
형식  1.109971  1.023776  0.000000


In [24]:
print(distDF)

선형        영채        형식
선형  0.000000  0.921644  1.109971
영채  0.921644  0.000000  1.023776
형식  1.109971  1.023776  0.000000


In [31]:
model.wv.most_similar("형식")

[('영채', -0.023776261135935783), ('선형', -0.10997101664543152)]

In [ ]:
###############################이하 연습장########################

In [28]:
from konlpy.tag import Twitter; t = Twitter()

pos = lambda d: ['/'.join(p) for p in t.pos(d)]

texts_ko = [pos(doc) for doc in docs_ko]

NameError: name 'docs_ko' is not defined

In [37]:
from gensim.models import word2vec

wo=[]
for w in noun_adj:
    if len(w)>1:
        wo.append(w)
        
wv_model_ko = word2vec.Word2Vec(wo)

wv_model_ko.init_sims(replace=True)

In [1]:
print(wv_model_ko)

NameError: name 'wv_model_ko' is not defined

In [35]:
wv_model_ko.save('ko_word2vec_e.model')

In [36]:
print(list(wv_model_ko.wv.vocab.keys()))

['여', '섯', '체', '험', '이', '야', '기', '제', '목', '원', '시', '림', '그', '하', '나', '수', '보', '아', '구', '렁', '것', '린', '어', '통', '짝', '동', '안', '소', '화', '밀', '모', '대', '해', '한', '참', '생', '각', '고', '색', '연', '필', '가', '지', '름', '애', '작', '품', '른', '자', '답', '코', '끼', '리', '명', '차', '라', '역', '사', '계', '산', '문', '법', '관', '심', '직', '업', '포', '호', '성', '공', '스', '로', '니', '노', '릇', '다', '선', '비', '행', '조', '종', '세', '저', '거', '의', '도', '움', '번', '중', '국', '별', '주', '일', '람', '까', '금', '만', '날', '간', '예', '으', '례', '프', '정', '치', '매', '우', '청', '년', '몹', '막', '장', '마', '음', '상', '터', '군', '데', '승', '혼', '천', '양', '운', '무', '얼', '러', '분', '방', '내', '굴', '력', '잘', '못', '때', '외', '습', '든', '실', '피', '두', '신', '듯', '되', '풀', '부', '인', '누', '위', '은', '벌', '써', '친', '미', '건', '찬', '절', '디', '판', '새', '바', '개', '머', '왕', '질', '령', '처', '물', '씨', '늘', '르', '불', '득', '존', '재', '줄', '걸', '멀', '오', '짐', '말', '웃', '돌', '백', '망', '경', '학', '발', '견', '혹', '당', '증', '식', '입', '형', '요', '숫', '엇', '버', '약', '벽',

In [47]:
from gensim.models import Word2Vec
embedding_model = Word2Vec(noun_adj, size=100, window = 2, min_count=50, workers=4, iter=100, sg=1)

In [48]:
print(list(embedding_model.wv.vocab.keys()))

['여', '나', '이', '기', '제', '시', '그', '하', '수', '보', '아', '구', '위', '것', '어', '소', '모', '대', '해', '생', '각', '고', '난', '가', '지', '내', '른', '자', '답', '리', '사', '문', '로', '다', '저', '거', '도', '별', '때', '주', '일', '람', '우', '장', '마', '물', '양', '무', '말', '바', '왕', '오', '너', '꽃']
